// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzfP-4L4SDVlSJKXkDEwRsiKeY3NCPWlU',
    appId: '1:384156467229:web:47045da116366193e5c6f4',
    messagingSenderId: '384156467229',
    projectId: 'quizzizz-users',
    authDomain: 'quizzizz-users.firebaseapp.com',
    storageBucket: 'quizzizz-users.firebasestorage.app',
    measurementId: 'G-BWDC7WREFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXkmzKC3vrw4r0pw3h450FXe1IWWnBOs',
    appId: '1:384156467229:android:a8325807aef356f8e5c6f4',
    messagingSenderId: '384156467229',
    projectId: 'quizzizz-users',
    storageBucket: 'quizzizz-users.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-jG11a8CUvuMNzcqNcWVoor3ytPHjrs',
    appId: '1:384156467229:ios:967249ae33c7f2e7e5c6f4',
    messagingSenderId: '384156467229',
    projectId: 'quizzizz-users',
    storageBucket: 'quizzizz-users.firebasestorage.app',
    iosClientId: '384156467229-3q1shdda1161i0at5t8rqpro2brrmujo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzizzClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-jG11a8CUvuMNzcqNcWVoor3ytPHjrs',
    appId: '1:384156467229:ios:967249ae33c7f2e7e5c6f4',
    messagingSenderId: '384156467229',
    projectId: 'quizzizz-users',
    storageBucket: 'quizzizz-users.firebasestorage.app',
    iosClientId: '384156467229-3q1shdda1161i0at5t8rqpro2brrmujo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzizzClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzfP-4L4SDVlSJKXkDEwRsiKeY3NCPWlU',
    appId: '1:384156467229:web:ccc90373219f4da8e5c6f4',
    messagingSenderId: '384156467229',
    projectId: 'quizzizz-users',
    authDomain: 'quizzizz-users.firebaseapp.com',
    storageBucket: 'quizzizz-users.firebasestorage.app',
    measurementId: 'G-31PBNN2ZG8',
  );
}
